WIP: CO2 table image
Klimatbyran/data-pipeline pull request #40
Opened 2024-02-20 08:32 UTC by irony

Try it out by opening a browser to localhost:3000/api/companies (this is a testing route to be able to quickly iterate without Discord)

TODO: Add all Scope 2 fields and create another method for generating Scope 3

Solves: #25

2024-02-20 08:34 UTC, irony commented
Just nu ser tabellen ut så här, ska bli finare med lite css:

![image](https://github.com/Klimatbyran/data-pipeline/assets/395843/4352a30a-e8f9-4def-b970-7979c1c459dd)

2024-02-29 16:11 UTC, irony commented
Nu är denna redo för review. Så här ser data ut från den json som vi har nu:
![image](https://github.com/Klimatbyran/data-pipeline/assets/395843/d354884b-7f54-4c42-bf44-0438ee88e9d4)

Jag har inte kunnat testa med Discord pga vi har bara en token/bot men jag tror att det ska fungera så som den är skriven nu.

2024-03-01 07:02 UTC, schweinryder requested changes

2024-03-01 07:02 UTC, schweinryder commented on src/prompts/parsePDF.ts
> +      "emissions": [
stäng den här arrayen

2024-03-06 10:41 UTC, irony commented
TACK! Ska fixa enligt dessa

2024-03-14 08:40 UTC, merged